insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '문과 남자의 과학공부', 15750, '/com/itwill/shop/image/bestSeller1', '유시민이 들려주는 과학 인문학이야기',10);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '스킵과 로퍼 6', 5400, '/com/itwill/shop/image/bestSeller2', '도쿄 고교생활 속 연애이야기',10);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '도둑맞은 집중력', 16920, '/com/itwill/shop/image/bestSeller3', '삶에서 도난당하고 있는 집중력을 되찾는법을 담은책',10);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '스튜디오 지브리 입체건축전 도록', 27000, '/com/itwill/shop/image/bestSeller4', '스튜디오 지브리 입체건축전 전시회 도록',10);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '세이노의가르침', 6480, '/com/itwill/shop/image/selfImprovement1', '순자산 천억원대 자산가의 인생이야기',20);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '최적의공부뇌', 15120, '/com/itwill/shop/image/selfImprovement2', '공부를 잘하기 위한 최소조건인 뇌의최적화에 대해',20);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '역행자 확장판', 17550, '/com/itwill/shop/image/selfImprovement3', '운명과 본능의 지배에서 벗어나 경제적 자유와 행복을 쟁취하는 라이프해킹의 비밀을 담은 책',20);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '사장학개론', 22500, '/com/itwill/shop/image/selfImprovement4', '한국과 미국, 전 세계를 오가며 ‘사장을 가르치는 사장’으로 알려진 『돈의 속성』의 저자 김승호 회장의 신간',20);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '꿀벌의예언1', 15120, '/com/itwill/shop/image/novel1', '꿀벌이 사라진 지구를 예언서로 구하는 이야기',30);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '있을법한모든것', 13500, '/com/itwill/shop/image/novel2', '우리도한번쯤상상해봤을또는 상상하지못한 이야기',30);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '꿀벌의예언2', 15120, '/com/itwill/shop/image/novel3', '꿀벌이 사라진 지구를 예언서로 구하는 이야기',30);
insert into product(p_no,p_name,p_price,p_image,p_desc,p_category) values(product_p_no_SEQ.nextval, '나니아 연대기 (리커버 특별판)', 67500, '/com/itwill/shop/image/novel4', '나니아 연대기 시리즈 총 7편을 하나로 묶은 합본의 특별판',30);
